Review
OlgaKg/movies-explorer-frontend pull request #1
Opened 2023-09-22 00:53 UTC by OlgaKg

2023-09-22 05:57 UTC, Savallera requested changes
# Резюме по работе:

Здравствуйте!
У Вас получилась хорошая работа для первого раза. Будет еще 3 итерации для того, чтобы над ней можно было еще поработать и она выгодно смотрелась в Вашем портфолио.
Вносите правки без спешки, следите за тем, что изменилось после внесения той или иной правки в элементе. Убедитесь перед отправкой, что все правки внесены. Если есть трудности - обращайтесь к наставнику и старшему студенту, они обязательно Вам помогут.

## Верстка и JSX

### Критерии, влияющие на работоспособность
- [ ] <!--12--> Все блоки и элементы из макета сверстаны. Размеры и расположение не отличаются от макета на более, чем на 30px на десктопной версии и на 10px на остальных размерах экрана, для которых подготовлен макет. Отличия в размерах не должны визуально противоречить макету и выбиваться из заложенной в макет сетки, в этом случае требуется более строгое соответствие размерам макета.

	* Контент тянется на весь экран на больших мониторах, хорошо бы добавить ему фиксацию по макету (1280пх) и центрировать относительно вьюпорта. В этом могут помочь сво-ва max-width, margin.
	* Стр. Вход/Рег. - подвал по макету не размещен (он появляется когда с главной переходишь на Вход, а когда возвращаешься он на главной пропадает)
	* https://yadi.sk/d/lYiTf4N3a8z59Q https://yadi.sk/d/fZq7Xl5gyeUdVw Меню размещен бургер
	* https://yadi.sk/d/hDv6tCBblVMMkg В фильмах шапка авторизованного не отображается
	* https://yadi.sk/d/BV_RLM963FKWTQ стиль не по макету

	* 404 - https://yadi.sk/d/mWWUALy_YXNJkQ https://yadi.sk/d/g5r-i9Lwqr09GA https://yadi.sk/d/p30FRaP1EIiuSA отступ
	* Профиль - 320 https://yadi.sk/d/tzdKF0inO5RASw
	* Главная - 768 https://yadi.sk/d/J12akxeyqc1PnA / 320 https://yadi.sk/d/fZq7Xl5gyeUdVw https://yadi.sk/d/kcAalL-IqlKIXw
	* Вход 1280/768 https://yadi.sk/d/Z4-4llGNDoMrRg
	* Регистрация/Вход 320 https://yadi.sk/d/YVqJm9LJY3dFSQ
	* Сохр.фильмы - все разрешения - https://yadi.sk/d/qnOJWI7j2oARpA отступ до подвала
	* Меню https://yadi.sk/d/MazETe94ONw6Ew https://yadi.sk/d/Fqy6_ir7TrXe6g

- [ ] <!--10.55--> Проект адаптирован под различные разрешения экрана. Горизонтальный скролл не возникает на разрешениях от 320 пикселей и больше. Нельзя скрывать полосу прокрутки свойством overflow: hidden.

	- Главная/Вход/Рег/Фильмы/Сох - Обратите внимание, что при сужении экрана образуется горизонтальный скролл. Это чаще всего происходит когда элементы не влезают по ширине, стоит проверить фиксированные ширины, размеры заголовков и перестройку сетки на брейкпоинтах, внести соотв. изменения. Помните также, что медиа запросы должны быть сгруппированы, не менее 150-200п разницей.

- [x] <!--9.55--> Корректно работает навигация между страницами и ссылки на внешние ресурсы: ни одна ссылка не ведёт в пустоту или на якорь, внешние ссылки открываются в новой вкладке. На все страницы проекта можно попасть, а скрытые блоки можно отобразить.

	- Выйти из профиля - добавьте переход на Главную/Логин

- [ ] <!--5.55--> Именование классов сделаны по БЭМ.

	- в проекте есть ошибки БЭМ, воспользуйтесь валидатором для проверки https://nglazov.github.io/bem-validator-page/
	- aboutMe, moviesCardList - придерживайтесь одной стилистили в именовании классов, так в большинстве случаев используйется кебаб-кейс about-me. Скорректируйте весь проект на аналогичные замечания.
	- auth__form_login - здесь хорошо подойдут сложные модификаторы БЭМ, напр., auth__form_place_login (также можно с полями и кнопками auth__input-password auth__btn-login и т.д. это их сгруппирует и при поддержке можно будет четко понимать, что они группируются вместе, а не два разных элемента, независимых.)
	- https://yadi.sk/d/W_WVeCICcYQVHA хорошо бы использование модификаторов БЭМ вместо инлайновых стилей

- [ ] <!--8.55--> Отзывчивая вёрстка, которая корректно тянется на всех промежуточных разрешениях.

	- https://yadi.sk/d/20PkeSAR0Om_uQ https://yadi.sk/d/MmpMIXpwqMGq7Q контент следует сделать отзывчивым на всех устройствах. Также обратите внимание, что на страницах 404, профиль, регистрация и вход в макете выравнивание по вертикали идет относительно высоты вьюпорта, это значит, что на любых других устройствах оно должно центрироваться без фиксации высоты по макету не образовывая вертикальный скролл. Для реализации можно использовать технологию построения через флекс/грид, когда контент центрируется, шапка прижата к верху, футер к низу. Можно лучше на главной сделать липкий футер прижав хедер и растянув основной контент [Как создать липкий футер с помощью flexbox](https://webformyself.com/kak-sozdat-lipkij-futer-s-pomoshhyu-flexbox/).
	- https://yadi.sk/d/rS2-r7EmdoWsYQ при сужении карточки разносятся в разные стороны, можно центрировать или сделать ширину отзывчивой через относительные величины
	- https://yadi.sk/d/BFNz6sel7exoyg https://yadi.sk/d/uzFYmKRxVOVE2w В любом месте где есть контент не следует делать фиксацию по высоте, т.к. контент может измениться и это не должно поломать отображение. Если блок содержит фоновое изображение и контент используйте минимальную высоту, Вам следует самостоятельно на примере найти и исправить все похожие случаи

- [ ] <!--3.38--> В коде используется семантическая разметка: применяются семантические теги, выбор элементов при вёрстке корректен (параграф должен быть параграфом, список — списком); структура DOM-дерева состоит не только из контейнеров div.

	- aboutMe__container-foto - можно без дива-обертки, чтобы разметка была чище
	- movies-card__remove-button оформите кнопкой вместо дива, movies-card__saved-icon и movies-card__save-btn - это один смысловой элемент, ему также будет нужен одинаковый класс по БЭМ, отличия можно уточнить модификаторами
	- navigation__account-icon, portfolio__icon, promo__logo-landing, search-form__search-icon - Хорошей практикой считается отображать декоративные изображения/иконки на псевдоклассах `:before` и `:after` https://habr.com/ru/post/154319/
	- Каждой отдельной странице нужен заголовок 1 уровня (Вход/Рег/Профиль/404)
	- Каждый основной контент на странице следует обернуть main, все кроме header и footer (Вход/Рег/Профиль/404)
	- techs нарушена иерархия заголовков относительно данной секции
	- techs__list - хорошо бы семантическим списком оформить

- [ ] <!--3.38--> Для позиционирования элементов выбран верный подход, описанный корректным синтаксисом.

	- promo__title - разместите в поточном режиме, чтбы не вырывать контент

- [x] <!--3.38--> Каркас макета реализован на Flex layout или Grid layout;
- [x] <!--3.38--> Инфраструктурные файлы проекта созданы через CRA.
- [ ] <!--3.38--> Работа модальных окон настроена.

	- https://yadi.sk/d/FLulr-3vifOJYA - ошибки в консоли после попытки авторизоваться

- [ ] Разметка портирована в JSX:
	- [x] <!--3.38--> разметка заключена в ( ), лишние пустые <div> для этого не используются;
	- [x] <!--3.38--> разметка вынесена в соответствующие ей компоненты.
- [ ] В проекте есть:
	- [x] <!--3.38--> директория images/ с картинками,
	- [x] <!--3.38--> директория components/ с JS и CSS-файлами компонентов,
	- [x] <!--3.38--> директория fonts/ со шрифтами.

### Хорошие практики
- [ ] <!--2.14--> Кнопки, инпуты и ссылки реализованы во всех состояниях, указанных в макете.

	- Лого, якорных ссылок на главной - нет ховер эффекта
	- search-form__filter-label - оформите селектором label и при помощи атрибута for соедините с чекбоксом через id, для переключения состояния.
	- notFound__backBtn - нет курсора/ховер эффекта
	- https://yadi.sk/d/bomgKX72ykaUyA нет ховер эффекта
	- кнопочкам в фильмах также добавьте ховер

- [x] <!--2.14--> В макете есть одинаковые элементы. Для их оформления должен быть переиспользован один компонент.
- [x] <!--2.14--> Шрифты подключены через @font-face.
- [x] <!--2.14--> Иконки экспортированы в формате SVG.
- [ ] <!--2.14--> Элементы формы должны выделяться, когда на них установлен фокус. Состояние фокуса, а также outline стилизованы в соответствии с макетом или на своё усмотрение.

	- Всем полям следует стилизовать состояния focus и outline по макету или на свое усмотрение, чтобы [...]

2023-09-24 12:23 UTC, Savallera requested changes
# Резюме по работе:

Здравствуйте!
Готово 2 ревью на Ваш проект, неплохая работа по замечаниям, добавила Вам баллов. Есть еще моменты, которым следует уделить внимание. Уверена, что у Вас все получится.

## Верстка и JSX

### Критерии, влияющие на работоспособность
- [ ] <!--12--> Все блоки и элементы из макета сверстаны. Размеры и расположение не отличаются от макета на более, чем на 30px на десктопной версии и на 10px на остальных размерах экрана, для которых подготовлен макет. Отличия в размерах не должны визуально противоречить макету и выбиваться из заложенной в макет сетки, в этом случае требуется более строгое соответствие размерам макета.

	* 404 - 768 https://yadi.sk/d/7Aos8zdWNXnU_g
	* 768 https://yadi.sk/i/AAaBmwtsRzwYZg
	* 320 https://yadi.sk/i/-3VwiQA2wKPpZQ https://yadi.sk/i/T2uIRxMdHOiofw
	* Подвал - https://yadi.sk/i/eyZkp6llDHdbCA
	* Шапка https://yadi.sk/d/GrpWhUlXIp-EpA

- [ ] <!--10.55--> Проект адаптирован под различные разрешения экрана. Горизонтальный скролл не возникает на разрешениях от 320 пикселей и больше. Нельзя скрывать полосу прокрутки свойством overflow: hidden.

	- https://yadi.sk/d/JFL6tU-U2BaFow https://yadi.sk/d/n3YFZy6g1OoyYg - Сохраняется замечание. При сужении экрана образуется горизонтальный скролл. Это чаще всего происходит когда элементы не влезают по ширине, стоит проверить фиксированные ширины, размеры заголовков и перестройку сетки на брейкпоинтах, внести соотв. изменения. Помните также, что медиа запросы должны быть сгруппированы, не менее 150-200п разницей.

- [x] <!--9.55--> Корректно работает навигация между страницами и ссылки на внешние ресурсы: ни одна ссылка не ведёт в пустоту или на якорь, внешние ссылки открываются в новой вкладке. На все страницы проекта можно попасть, а скрытые блоки можно отобразить.
- [ ] <!--5.55--> Именование классов сделаны по БЭМ.

	- https://yadi.sk/d/bUVkJLo_gCUy0g сохраняются ошибки БЭМ, воспользуйтесь валидатором для проверки https://nglazov.github.io/bem-validator-page/
	- not-found__backBtn - в проекте еще встречаются кэмалКейс
	- header_home - здесь также хорошо подойдут сложные модификаторы БЭМ, напр., header_place_home

- [ ] <!--8.55--> Отзывчивая вёрстка, которая корректно тянется на всех промежуточных разрешениях.

	- https://yadi.sk/i/OR_DNMDyDqB-zQ https://yadi.sk/i/7X8KsuaFUgY2Uw при сужении элементы не равномерно уменьшаются. Хорошо помогает перенос на сл.строку, также относительные размеры, что делает элементы отзывчивыми
	- https://yadi.sk/d/-MD26VMdd89ITg https://yadi.sk/d/MmpMIXpwqMGq7Q контент следует сделать отзывчивым на всех устройствах. Также обратите внимание, что на страницах 404, профиль, регистрация и вход в макете выравнивание по вертикали идет относительно высоты вьюпорта, это значит, что на любых других устройствах оно должно центрироваться без фиксации высоты по макету не образовывая вертикальный скролл. Для реализации можно использовать технологию построения через флекс/грид, когда контент центрируется, шапка прижата к верху, футер к низу. Можно лучше на главной сделать липкий футер прижав хедер и растянув основной контент [Как создать липкий футер с помощью flexbox](https://webformyself.com/kak-sozdat-lipkij-futer-s-pomoshhyu-flexbox/).
	- https://yadi.sk/d/onwGbKZGxTLv5A при сужении карточки прижаты к левому краю, можно центрировать или сделать ширину отзывчивой через относительные величины

- [ ] <!--3.38--> В коде используется семантическая разметка: применяются семантические теги, выбор элементов при вёрстке корректен (параграф должен быть параграфом, список — списком); структура DOM-дерева состоит не только из контейнеров div.

	- about-me__container-foto - можно без дива-обертки, чтобы разметка была чище
	- movies-card__remove-button оформите кнопкой вместо дива
	- navigation__account-icon, portfolio__icon, search-form__search-icon - Хорошей практикой считается отображать декоративные изображения/иконки на псевдоклассах `:before` и `:after` https://habr.com/ru/post/154319/
	- Каждый основной контент на странице следует обернуть main, все кроме header и footer (Вход/Рег/Профиль/404)
	- techs__title-description - подзаголовок не может быть такого же уровня как и заголовок секции, здесь хорошо будет параграфом или 3 уровнем
	- techs__list - хорошо бы семантическим списком оформить

- [x] <!--3.38--> Для позиционирования элементов выбран верный подход, описанный корректным синтаксисом.
- [x] <!--3.38--> Каркас макета реализован на Flex layout или Grid layout;
- [x] <!--3.38--> Инфраструктурные файлы проекта созданы через CRA.
- [x] <!--3.38--> Работа модальных окон настроена.
- [ ] Разметка портирована в JSX:
	- [x] <!--3.38--> разметка заключена в ( ), лишние пустые <div> для этого не используются;
	- [x] <!--3.38--> разметка вынесена в соответствующие ей компоненты.
- [ ] В проекте есть:
	- [x] <!--3.38--> директория images/ с картинками,
	- [x] <!--3.38--> директория components/ с JS и CSS-файлами компонентов,
	- [x] <!--3.38--> директория fonts/ со шрифтами.

### Хорошие практики
- [x] <!--2.14--> Кнопки, инпуты и ссылки реализованы во всех состояниях, указанных в макете.
- [x] <!--2.14--> В макете есть одинаковые элементы. Для их оформления должен быть переиспользован один компонент.
- [x] <!--2.14--> Шрифты подключены через @font-face.
- [x] <!--2.14--> Иконки экспортированы в формате SVG.
- [ ] <!--2.14--> Элементы формы должны выделяться, когда на них установлен фокус. Состояние фокуса, а также outline стилизованы в соответствии с макетом или на своё усмотрение.

	- https://yadi.sk/d/i5yZxFookZaK0g У полей прозрачный фокус (нужно чтобы был виден), также добавьте видимый фокус в профиль и поиск

- [ ] <!--2.14--> У формы должны быть заданы плейсхолдеры, валидированы обязательные поля.

	- Всем <form> хорошо бы добавить атрибут name

- [x] <!--2.14--> reset.css запрещен.

### Рекомендации
- [x] <!--1.68--> Для каждого шрифта указаны альтернативные варианты из системных шрифтов.
- [x] <!--1.67--> Для изображений задан атрибут alt с подходящий значением.
- [x] <!--1.67--> Растровые и векторные изображения оптимизированы;

## Количество баллов: 56

## Доп. Комментарии:
- <html lang="en"> - язык проекта русский

2023-09-26 15:44 UTC, Savallera approved these changes
# Резюме по работе:

Здравствуйте! 
Поздравляю, Ваш проект принят! Желаю Вам дальнейших успехов во всех начинаниях!

## Верстка и JSX

### Критерии, влияющие на работоспособность
- [x] <!--12--> Все блоки и элементы из макета сверстаны. Размеры и расположение не отличаются от макета на более, чем на 30px на десктопной версии и на 10px на остальных размерах экрана, для которых подготовлен макет. Отличия в размерах не должны визуально противоречить макету и выбиваться из заложенной в макет сетки, в этом случае требуется более строгое соответствие размерам макета.
- [ ] <!--10.55--> Проект адаптирован под различные разрешения экрана. Горизонтальный скролл не возникает на разрешениях от 320 пикселей и больше. Нельзя скрывать полосу прокрутки свойством overflow: hidden.

	- https://yadi.sk/d/2tks3L1ihTh3YQ - Сохраняется замечание. При сужении экрана образуется горизонтальный скролл. Это чаще всего происходит когда элементы не влезают по ширине, стоит проверить фиксированные ширины, размеры заголовков и перестройку сетки на брейкпоинтах, внести соотв. изменения. Помните также, что медиа запросы должны быть сгруппированы, не менее 150-200п разницей.

- [x] <!--9.55--> Корректно работает навигация между страницами и ссылки на внешние ресурсы: ни одна ссылка не ведёт в пустоту или на якорь, внешние ссылки открываются в новой вкладке. На все страницы проекта можно попасть, а скрытые блоки можно отобразить.
- [x] <!--5.55--> Именование классов сделаны по БЭМ.
- [x] <!--8.55--> Отзывчивая вёрстка, которая корректно тянется на всех промежуточных разрешениях.
- [x] <!--3.38--> В коде используется семантическая разметка: применяются семантические теги, выбор элементов при вёрстке корректен (параграф должен быть параграфом, список — списком); структура DOM-дерева состоит не только из контейнеров div.
- [x] <!--3.38--> Для позиционирования элементов выбран верный подход, описанный корректным синтаксисом.
- [x] <!--3.38--> Каркас макета реализован на Flex layout или Grid layout;
- [x] <!--3.38--> Инфраструктурные файлы проекта созданы через CRA.
- [x] <!--3.38--> Работа модальных окон настроена.
- [ ] Разметка портирована в JSX:
	- [x] <!--3.38--> разметка заключена в ( ), лишние пустые <div> для этого не используются;
	- [x] <!--3.38--> разметка вынесена в соответствующие ей компоненты.
- [ ] В проекте есть:
	- [x] <!--3.38--> директория images/ с картинками,
	- [x] <!--3.38--> директория components/ с JS и CSS-файлами компонентов,
	- [x] <!--3.38--> директория fonts/ со шрифтами.

### Хорошие практики
- [x] <!--2.14--> Кнопки, инпуты и ссылки реализованы во всех состояниях, указанных в макете.
- [x] <!--2.14--> В макете есть одинаковые элементы. Для их оформления должен быть переиспользован один компонент.
- [x] <!--2.14--> Шрифты подключены через @font-face.
- [x] <!--2.14--> Иконки экспортированы в формате SVG.
- [x] <!--2.14--> Элементы формы должны выделяться, когда на них установлен фокус. Состояние фокуса, а также outline стилизованы в соответствии с макетом или на своё усмотрение.
- [x] <!--2.14--> У формы должны быть заданы плейсхолдеры, валидированы обязательные поля.
- [x] <!--2.14--> reset.css запрещен.

### Рекомендации
- [x] <!--1.68--> Для каждого шрифта указаны альтернативные варианты из системных шрифтов.
- [x] <!--1.67--> Для изображений задан атрибут alt с подходящий значением.
- [x] <!--1.67--> Растровые и векторные изображения оптимизированы;

## Количество баллов: 89

* Шапку немного скорректируйте https://yadi.sk/d/mtWvBxMSG7bWMQ

2023-09-26 16:34 UTC, OlgaKg commented
Спасибо за проверку)Хотела уточнить, на рабой ширине проблема. с шапкой? А то я что то найти не могу

2023-09-27 10:55 UTC, merged